// corpus.js — what notes, sources and tags currently exist.
//
// Three pickers depend on this: the book picker, the wiki-link picker, and the tag
// type-ahead. Each exists to stop a class of drift the repo has already suffered:
//
//   • wiki-link picker — a `[[link]]` whose target does not exist is invisible to
//     both validators (a known hole, found the hard way during the Chaucer ingest),
//     so links are CHOSEN from real note ids and every generated note is checked for
//     dangling links before it can be committed.
//   • tag type-ahead — 2,600 tags are already in use; typing them freehand mints a
//     sixth spelling of one idea.
//   • book picker — reading lives under raw-notes/commons/reading/<source-id>/, and
//     the source-id is what a book note's `source:` must match.
//
// Two sources of truth, merged:
//   BAKED  public/data/notes-index.json — generated by scripts/build-index.mjs from
//          the checkout. Carries TITLES (which the git tree does not) and works with
//          no token, offline, and on first paint. Freezes at the commit it was built
//          from.
//   LIVE   the repo's git tree via the GitHub API, when GITHUB_REPO is configured.
//          Carries every note that exists RIGHT NOW, but only paths.
//
// Merging gives titles where we have them and freshness everywhere: a note created
// since the last bake shows up (titled from its filename), and a note deleted since
// the bake disappears.

import { listNotes } from "./github.js";

let _baked = null;

/** Load (and memoise) the baked index through the static-assets binding. */
export async function bakedIndex(env) {
  if (_baked) return _baked;
  try {
    const r = await env.ASSETS.fetch(new Request("https://scribe.local/data/notes-index.json"));
    if (!r.ok) throw new Error(`assets ${r.status}`);
    _baked = await r.json();
  } catch {
    _baked = { generated: null, sources: [], tags: [], notes: [], counts: { notes: 0, sources: 0, tags: 0 } };
  }
  return _baked;
}

const prettify = (stem) =>
  String(stem)
    .replace(/^\d{4}-\d{2}-\d{2}-/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

/**
 * corpus — the merged view.
 * Returns { notes:[{id,title,path,dir}], sources:[{id,title,notes}], tags:[], live, generated }.
 */
export async function corpus(env) {
  const baked = await bakedIndex(env);
  const byPath = new Map();
  for (const n of baked.notes || []) {
    byPath.set(n.p, { id: n.i, title: n.t || prettify(n.i), path: n.p, dir: n.d });
  }

  let live = false;
  if (env.GITHUB_REPO) {
    try {
      const tree = await listNotes({ repo: env.GITHUB_REPO, branch: env.GITHUB_BRANCH || "main", token: env.GITHUB_TOKEN });
      if (tree.ok && tree.files.length) {
        live = true;
        const seen = new Set();
        for (const f of tree.files) {
          seen.add(f.path);
          if (byPath.has(f.path)) continue;
          const parts = f.path.split("/");
          const stem = parts.at(-1).replace(/\.md$/, "");
          if (stem === "index" || stem === "README") continue;
          byPath.set(f.path, { id: stem, title: prettify(stem), path: f.path, dir: parts[1], new: true });
        }
        // Drop anything the bake still remembers but the repo no longer has.
        for (const p of [...byPath.keys()]) if (!seen.has(p)) byPath.delete(p);
      }
    } catch {
      live = false; // a GitHub hiccup must never break capture — the bake carries on
    }
  }

  const notes = [...byPath.values()].sort((a, b) => a.id.localeCompare(b.id));

  // Sources: the baked list (it has real titles), plus any reading directory that
  // has appeared live since the bake.
  const sources = [...(baked.sources || [])];
  if (live) {
    const known = new Set(sources.map((s) => s.id));
    for (const n of notes) {
      const m = n.path.match(/^raw-notes\/commons\/reading\/([^/]+)\//);
      if (m && !known.has(m[1])) {
        known.add(m[1]);
        sources.push({ id: m[1], title: prettify(m[1]), notes: 0, new: true });
      }
    }
    sources.sort((a, b) => a.id.localeCompare(b.id));
  }

  return { notes, sources, tags: baked.tags || [], live, generated: baked.generated };
}

/** The set of ids a `[[wiki-link]]` may resolve to. */
export async function knownIds(env) {
  const { notes } = await corpus(env);
  return new Set(notes.map((n) => n.id));
}

/**
 * Which of a note's wiki-links point at nothing. The lake resolves links by id
 * across folders and IS case-sensitive, so the comparison here is too.
 */
export async function danglingLinks(env, links) {
  const ids = await knownIds(env);
  return (links || []).filter((l) => !ids.has(l));
}

/** Substring search over id + title, newest-looking matches first. */
export function searchNotes(notes, q, { dir = null, limit = 40 } = {}) {
  const needle = String(q || "").trim().toLowerCase();
  let out = notes;
  if (dir) out = out.filter((n) => n.dir === dir);
  if (needle) {
    out = out
      .map((n) => {
        const id = n.id.toLowerCase();
        const title = String(n.title || "").toLowerCase();
        if (id === needle) return [0, n];
        if (id.startsWith(needle)) return [1, n];
        if (title.startsWith(needle)) return [2, n];
        if (id.includes(needle)) return [3, n];
        if (title.includes(needle)) return [4, n];
        return null;
      })
      .filter(Boolean)
      .sort((a, b) => a[0] - b[0] || a[1].id.localeCompare(b[1].id))
      .map(([, n]) => n);
  }
  return out.slice(0, limit);
}
